name: "Release"

on:
    push:
        branches:
          - master

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@v5

          - name: Setup Node.js
            uses: actions/setup-node@v5
            with:
                node-version: 24
                registry-url: 'https://registry.npmjs.org'

          - name: Cache dependencies
            uses: actions/cache@v4
            with:
                path: ~/.npm
                key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
                restore-keys: |
                    ${{ runner.os }}-npm-

          - name: Install Dependencies
            shell: bash
            run: npm install

          - name: Test
            shell: bash
            run: npm run test

          - name: Build
            shell: bash
            run: npm run build

          - name: Upload build
            uses: actions/upload-artifact@v5
            with:
                name: "dist"
                path: ./dist
    tag:
        name: Tag
        runs-on: ubuntu-latest
        permissions:
            contents: write
        needs:
          - build
        steps:
          - name: Checkout code
            uses: actions/checkout@v5

          - name: Versions
            shell: bash
            run: |
                MAJOR=$(node -p "require('./package.json').version.split('.')[0]")
                MINOR=$(node -p "require('./package.json').version.split('.')[1]")
                PATCH=$(node -p "require('./package.json').version.split('.')[2]")
                echo "MAJOR=$MAJOR" >> $GITHUB_ENV
                echo "MINOR=$MINOR" >> $GITHUB_ENV
                echo "PATCH=$PATCH" >> $GITHUB_ENV

          - name: Setup GPG
            uses: ./.github/actions/setup-git-gpg
            with:
                id: ${{ vars.GPG_ID }}
                private-key: ${{ secrets.GPG_PRIVATE_KEY }}
                passphrase: ${{ secrets.GPG_PASSPHRASE }}

          - name: Setup git
            uses: ./.github/actions/setup-git
            with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - name: Checkout code
            uses: actions/checkout@v5
            with:
                ref: "release"

          - name: Download build
            uses: actions/download-artifact@v5
            with:
                name: "dist"

          - name: Create tag
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            shell: bash
            run: |
                TAG_VERSION="latest"
                MAJOR_VERSION="v${{ env.MAJOR }}"
                FULL_VERSION="v${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}"
                git add .
                git commit --allow-empty -S -m "Release latest"
                git tag -d $TAG_VERSION || true
                git tag -d $MAJOR_VERSION || true
                git tag -d $FULL_VERSION || true
                git tag -sf $TAG_VERSION -m "Release $FULL_VERSION"
                git tag -sf $MAJOR_VERSION -m "Release $FULL_VERSION"
                git tag -sf $FULL_VERSION -m "Release $FULL_VERSION"
                git push origin release
                git push origin $TAG_VERSION --force
                git push origin $MAJOR_VERSION --force
                git push origin $FULL_VERSION --force

